Feat/implement dashboard startup and grant points
arkavidia-hmif/itfest-frontend-8.0 pull request #32
Opened 2023-02-07 06:03 UTC by fernaldifz

beberapa notes:
- di dashboard ada tombol sign out, pas dipakai api nya kelihatannya ada warning method not allowed tetapi tetap bisa kelog out
- di bagian enter pin, setiap pin nya masih bisa lebih dari 1 angka. Contoh pin 1 itu bisa "11", pin 2 itu "2", dst jadi hasil akhirnya "1123456"
- page enterpin dan grant points aku satukan
- mungkin ada error yg terlewatkan

2023-02-07 15:19 UTC, rafirm29 requested changes

2023-02-07 15:19 UTC, rafirm29 commented on app/(startup)/s/dashboard/page.tsx
> +                    onClick={signOut}
ini kayanya jadi `onClick{() => signOut()}` ajaa biar fungsinya kepanggil dgn baik

2023-02-07 15:19 UTC, rafirm29 commented on app/(startup)/s/grant-points/page.tsx
> +                        toast.error('User dengan pin<' + userCode + '> tidak ditemukan. Harap coba lagi.');
ini toastnya minta ditambahin options untuk ditampilin di tengah bawah screen, bisa cek di docs https://fkhadra.github.io/react-toastify/introduction/

2023-02-07 15:19 UTC, rafirm29 commented on app/(startup)/s/grant-points/page.tsx
> +            grantPoints(userCode, totalPoint);
ini tambahin await

2023-02-07 15:54 UTC, fernaldifz commented on app/(startup)/s/grant-points/page.tsx
> +            grantPoints(userCode, totalPoint);
@rafirm29 dah kuupdate ya, btw yg punyaku jdnya ga pakai komponen enter pin dan checkbox, kalau yg lain ga pakai jg nanti mungkin bisa dihapus

2023-02-08 09:23 UTC, rafirm29 approved these changes

2023-02-08 09:24 UTC, merged