Feat: Create Dashboard Page for Admin
arkavidia-hmif/itfest-frontend-8.0 pull request #4
Opened 2023-01-23 06:43 UTC by DiziASP

![image](https://user-images.githubusercontent.com/58800976/213979812-62f96aba-cc85-485e-9dea-060586b7dd94.png)
Screenshot of expected result

2023-01-23 07:06 UTC, rafirm29 requested changes

2023-01-23 07:06 UTC, rafirm29 commented on components/Dashboard-Admin/Points.tsx
> +            <h6 className="font-archivo text-3xl text-white shadow-black tracking-wide">
ini untuk yg h6 kayanya gausah pake class lagii krn udah disetting default stylenya di tailwind

2023-01-23 07:07 UTC, rafirm29 requested changes

2023-01-23 07:07 UTC, rafirm29 commented on components/Dashboard-Admin/Merch.tsx
> +          <h6 className="font-archivo text-3xl tracking-wide leading-7">
ini jugaa

2023-01-23 07:07 UTC, rafirm29 commented on components/Dashboard-Admin/Merch.tsx
> +        <h6 className="font-archivo font-[900] text-3xl tracking-wide">
ini jugaa

2023-01-23 07:09 UTC, rafirm29 requested changes

2023-01-23 07:09 UTC, rafirm29 commented on components/Dashboard-Admin/Merch.tsx
> +import Stock from "@/app/dashboard-admin/icons/stock.svg";
untuk icons taro di directory `public/icons` ajaa

2023-01-23 11:39 UTC, DiziASP commented on components/Dashboard-Admin/Points.tsx
> +            <h6 className="font-archivo text-3xl text-white shadow-black tracking-wide">
Done kak, udah diubah semua yang h6 nya

2023-01-23 11:40 UTC, DiziASP commented on components/Dashboard-Admin/Merch.tsx
> +import Stock from "@/app/dashboard-admin/icons/stock.svg";
okei udah dipindahin kak ke public

2023-01-24 02:21 UTC, rafirm29 approved these changes

2023-01-24 02:27 UTC, merged